import { afterEach, describe, expect, it, vi } from "vitest";
import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { Workbench } from "../src/components/workbench";
const url = "https://gangnambeautyguide.com/en/clinics/test-clinic/";
const time = "2026-09-15T21:00:00Z";
const discovery = { id: "test-run", startedAt: time, finishedAt: time, sources: [{ url, kind: "clinic", discoveredFrom: ["sitemap"], discoveredAt: time }], totalFound: 1, omitted: 0, warnings: [], partial: false };
const page = { url, finalUrl: url, kind: "clinic", collectedAt: time, status: "no_review_section", httpStatus: 200, title: "Test Clinic", reviews: [], clinics: [{ name: "Test Clinic", url, pageUrl: url }], warnings: [], error: null, reportedReviewCount: null, truncated: false, stopRequested: false };
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals(); });
describe("live workbench actions", () => {
  it("disables every completed lens while allowing an unprocessed lens without recollecting", async () => {
    const spy = vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(Response.json(discovery)).mockResolvedValueOnce(Response.json({ pages: [page] }));
    const user = userEvent.setup();
    render(<Workbench />);
    await user.click(screen.getByRole("button", { name: "Scan website" }));
    await screen.findByText("/en/clinics/test-clinic/");
    for (const name of [/Missing information/, /Clinic identity/, /Review similarity/]) {
      await user.click(screen.getByRole("button", { name }));
      expect(screen.getByRole("button", { name: "Run analysis" })).toBeEnabled();
      await user.click(screen.getByRole("button", { name: "Run analysis" }));
      const completed = await screen.findByRole("button", { name: "Analysis complete" });
      expect(completed).toBeDisabled();
      await user.click(completed);
      expect(spy).toHaveBeenCalledTimes(2);
    }
    for (const name of [/Missing information/, /Clinic identity/, /Review similarity/]) {
      await user.click(screen.getByRole("button", { name }));
      expect(screen.getByRole("button", { name: "Analysis complete" })).toBeDisabled();
    }
    expect(screen.queryByRole("button", { name: /Use completed analysis|Run analysis again/ })).not.toBeInTheDocument();
    expect(spy).toHaveBeenCalledTimes(2);
  });
  it("requires two clicks, preserves collection on scenario change, invalidates it on a new scan", async () => {
    const spy = vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(Response.json(discovery)).mockResolvedValueOnce(Response.json({ pages: [page] })).mockResolvedValueOnce(Response.json({ ...discovery, id: "second", sources: [], totalFound: 0 }));
    const user = userEvent.setup();
    render(<Workbench />);
    expect(spy).not.toHaveBeenCalled();
    await user.click(screen.getByRole("button", { name: "Scan website" }));
    await screen.findByText("/en/clinics/test-clinic/");
    expect(spy).toHaveBeenCalledTimes(1);
    expect(screen.queryByText("Collected records, not conclusions.")).not.toBeInTheDocument();
    await user.click(screen.getByRole("button", { name: "Run analysis" }));
    await screen.findByText(/Collection finished: 1/);
    expect(spy).toHaveBeenCalledTimes(2);
    expect(spy.mock.calls[1][0]).toBe("/api/collect");
    expect(JSON.parse(spy.mock.calls[1][1]!.body as string)).toEqual({ urls: [url] });
    await user.click(screen.getByRole("button", { name: /Clinic identity/ }));
    expect(spy).toHaveBeenCalledTimes(2);
    expect(screen.getByRole("button", { name: "View collected data" })).toBeInTheDocument();
    expect(screen.queryByRole("dialog")).not.toBeInTheDocument();
    const timestamps = document.querySelector(".collection-progress")?.textContent;
    await user.click(screen.getByRole("button", { name: "Run analysis" }));
    expect(spy).toHaveBeenCalledTimes(2);
    expect(screen.getByText(/Reusing the collected dataset/)).toBeInTheDocument();
    expect(document.querySelector(".collection-progress")?.textContent).toBe(timestamps);
    await user.click(screen.getByRole("button", { name: /Review similarity/ }));
    await user.click(screen.getByRole("button", { name: "Run analysis" }));
    expect(spy).toHaveBeenCalledTimes(2);
    await user.click(screen.getByRole("button", { name: "Refresh sources" }));
    await screen.findByText(/No supported URLs were found/);
    expect(screen.queryByText("Collected records, not conclusions.")).not.toBeInTheDocument();
    expect(screen.queryByText("/en/clinics/test-clinic/")).not.toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Run analysis" })).toBeDisabled();
    expect(screen.queryByText(/Reusing the collected dataset/)).not.toBeInTheDocument();
  });
  it("presents source, lens and execution in that document order", () => {
    render(<Workbench />);
    const source = screen.getByRole("heading", { name: "Select your source" });
    const lens = screen.getByRole("heading", { name: "Choose your lens" });
    const execution = screen.getByRole("heading", { name: "Run your analysis" });
    expect(source.compareDocumentPosition(lens) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();
    expect(lens.compareDocumentPosition(execution) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();
    expect(screen.getByRole("radio", { name: /Gangnam Beauty Guide/ })).toBeChecked();
  });
  it("retains a partial run on another lens instead of silently retrying collection", async () => {
    const spy = vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(Response.json(discovery)).mockResolvedValueOnce(Response.json({ pages: [{ ...page, status: "robots_blocked", error: "Policy unavailable", stopRequested: true }] }));
    render(<Workbench />);
    await userEvent.click(screen.getByRole("button", { name: "Scan website" }));
    await screen.findByText("/en/clinics/test-clinic/");
    await userEvent.click(screen.getByRole("button", { name: "Run analysis" }));
    await screen.findByText(/Partial collection: 1/);
    await userEvent.click(screen.getByRole("button", { name: /Clinic identity/ }));
    await userEvent.click(screen.getByRole("button", { name: "Run analysis" }));
    expect(spy).toHaveBeenCalledTimes(2);
    expect(screen.getByText("Refresh sources to start a new collection attempt.")).toBeInTheDocument();
  });
  it("reports scan errors without filling the list with old or demo data", async () => {
    vi.spyOn(globalThis, "fetch").mockResolvedValue(Response.json({ error: "Source unavailable." }, { status: 502 }));
    render(<Workbench />);
    await userEvent.click(screen.getByRole("button", { name: "Scan website" }));
    expect(await screen.findByRole("alert")).toHaveTextContent("Source unavailable.");
    expect(screen.getByRole("button", { name: "Run analysis" })).toBeDisabled();
  });
  it("exports the displayed dataset and zero-eligible report without keys", async () => {
    const spy = vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(Response.json(discovery)).mockResolvedValueOnce(Response.json({ pages: [page] }));
    let exported = "";
    const OriginalBlob = Blob;
    vi.stubGlobal("Blob", class extends OriginalBlob { constructor(parts: BlobPart[], options?: BlobPropertyBag) { super(parts, options); exported = String(parts[0]); } });
    const createUrl = vi.fn(() => "blob:test");
    Object.defineProperty(URL, "createObjectURL", { configurable: true, value: createUrl });
    Object.defineProperty(URL, "revokeObjectURL", { configurable: true, value: vi.fn() });
    vi.spyOn(HTMLAnchorElement.prototype, "click").mockImplementation(() => {});
    render(<Workbench />);
    await userEvent.click(screen.getByRole("button", { name: "Scan website" }));
    await screen.findByText("/en/clinics/test-clinic/");
    await userEvent.click(screen.getByRole("button", { name: "Run analysis" }));
    await screen.findByText(/Collection finished: 1/);
    await userEvent.click(screen.getByRole("button", { name: "Download all analyses (JSON)" }));
    await waitFor(() => expect(createUrl).toHaveBeenCalledTimes(1));
    const file = JSON.parse(exported);
    expect(file.schemaVersion).toBe(7);
    expect(file).not.toHaveProperty("corrections");
    expect(file).not.toHaveProperty("humanReviewedReports");
    expect(spy.mock.calls.some(([url]) => String(url).includes("/api/corrections"))).toBe(false);
    expect(file.collection).toBeUndefined();
    expect(file.reports["deepseek:missing-information"].status).toBe("complete");
    expect(file.reports["deepseek:missing-information"].eligible).toBe(0);
    expect(file.exportType).toBe("analysis-report");
    expect(file.selectedProvider).toBe("deepseek");
    expect(exported).not.toContain('"key":');
    expect(file.selectedScenario).toBe("missing-information");
    expect(file.exportScope).toBe("all-lenses");
    expect(file.activeLensAtExport).toBe("missing-information");
    expect(createUrl).toHaveBeenCalledTimes(1);
    await userEvent.click(screen.getByRole("button", { name: "View collected data" }));
    await userEvent.click(screen.getByRole("button", { name: "Download collected data (JSON)" }));
    const collected = JSON.parse(exported);
    expect(collected.discovery.sources[0].url).toBe(url);
    expect(collected.collection.pages[0].title).toBe("Test Clinic");
    expect(collected.reports).toBeUndefined();
    expect(collected.exportType).toBe("collected-data");
  });
  it("cancels a scan and does not publish a late response", async () => {
    vi.spyOn(globalThis, "fetch").mockImplementation((_url, options) => new Promise((_resolve, reject) => options?.signal?.addEventListener("abort", () => reject(new DOMException("Aborted", "AbortError")))));
    render(<Workbench />);
    await userEvent.click(screen.getByRole("button", { name: "Scan website" }));
    await userEvent.click(await screen.findByRole("button", { name: "Cancel" }));
    await waitFor(() => expect(screen.getByRole("alert")).toHaveTextContent("Scan cancelled"));
    expect(screen.getByRole("button", { name: "Run analysis" })).toBeDisabled();
  });
});
